/*
USER TABLE
*/
CREATE TABLE USERS
(
    ID            UUID      NOT NULL PRIMARY KEY,
    NAME          TEXT      NOT NULL,
    PASSWORD      TEXT      NOT NULL,
    EMAIL         TEXT      NOT NULL,
    CREATED_AT    TIMESTAMP NOT NULL,
    LAST_MODIFIED TIMESTAMP NOT NULL,
    LAST_LOGIN    TIMESTAMP NULL,
    IS_ACTIVE     BOOL      NOT NULL
);

/*
USER_PHONE TABLE
*/
CREATE TABLE USERS_PHONES
(
    ID           UUID      NOT NULL PRIMARY KEY,
    USER_ID      UUID        NOT NULL,
    NUMBER       VARCHAR(20) NOT NULL,
    CITY_CODE    VARCHAR(2)  NOT NULL,
    COUNTRY_CODE VARCHAR(2)  NOT NULL,
    CONSTRAINT FK_USER_USER_PHONE FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
